### ISSUE TITLE
API response <> API documentation (different order and duplicate fields)

### ISSUE THREAD

**Issue by littleskunk** [Storj/metadisk-api#31]
1.)
get buckets, post buckets, get buckets/{id}, patch buckets/{id} different order:
```
{
	"user":"{e-mail}",
	"created":"2016-03-09T22:47:48.950Z",
	"name":"Skunk first bucket",
	"pubkeys":["{key}"],
	"status":"Active",
	"transfer":30,
	"storage":10,
	"id":"{id}"
}
```

2.)
post /buckets/{id}/tokens different order and duplicate token (token / id)

```
{
  "bucket":"{id}",
  "operation":"PUSH",
  "expires":"2016-03-12T15:23:42.813Z",
  "token":"9f7c94825122936aa37f64e5255c11a15b7506c704311e70be167f3141d3229f",
  "id":"9f7c94825122936aa37f64e5255c11a15b7506c704311e70be167f3141d3229f"
}
```

3.)
get /buckets/{id}/files different order and duplicate hash (hash / id). I guess 
put /buckets/{id}/files has the same problem.
```
{
	"bucket":"{id}",
	"filename":"Storj.jpg",
	"size":123269,
	"mimetype":"image/jpeg",
	"hash":"cc35d79ba935e0e347f6321d0f0010c36387d065",
	"id":"cc35d79ba935e0e347f6321d0f0010c36387d065"
}
```

4.)
get keys, post keys different order and duplicate key (key / id)
```
{
	"user":"{e-mail}",
	"key":"{key}",
	"id":"{key}"
}
```

**Comment by gordonwritescode** [comment]
Hey @littleskunk - I don't think this is a bug. JSON does not guarantee field order, so we should not expect the order to always be the same.

Regarding the duplicate fields, the cases where you see that are cases where the schema has been optimized to use one of the unique fields in the document as it's primary key (for more efficient indexing), which is why the `id` field duplicates the `key` or `hash` field, etc. The `key`, `hash`, etc fields are *virtual* and are added to the response to more clearly describe the value than `id` does.

We could remove `id` from those responses, but I think it might be better to keep it for consistency with other schemas who are not optimized in that manner.
