### ISSUE TITLE
Broken pipe after a couple minutes while trying to upload 20MB file

### ISSUE THREAD

**Issue by hwkns** [Storj/metadisk-api#47]
I'm trying to test out downloading a file as multiple shards from multiple channels, but I can't seem to upload a file that is large enough to be split.  After a couple minutes of waiting, I get `Connection aborted: Broken pipe`.

**Comment by zoro1** [comment]
The largest file i am able to upload is 5MB

**Comment by gordonwritescode** [comment]
Thanks for reporting, will investigate

**Comment by gordonwritescode** [comment]
I have a strong suspicion that this is due to 1 farmer that is running the old BinaryJS implementation of the DataChannel. That would cause the "broken pipe". I was able to successfully upload a 26mb file and retrieve it - and the difference was that the farmers who won the storage contracts were running the latest DataChannel code.

We will deploy an update that enforces protocol version matching between peers and I think that will resolve this issue.

**Comment by gordonwritescode** [comment]
I have not been able to reproduce this since the aforementioned update. If it persists for any of you, let me know and we'll reopen it.

**Comment by zoro1** [comment]
i have uploaded a 25MB file but i cannot upload a 50MB. What is the limit?

**Comment by gordonwritescode** [comment]
There is no hard limit, did you get the same response? "Broken pipe"?

**Comment by zoro1** [comment]
I never got any response from api.metadisk.org. I just see that the file is not uploaded after a while.

**Comment by gordonwritescode** [comment]
Okay, good. I think the original issue here is resolved (`Broken pipe`). I think this new issue you are having will be resolved with https://github.com/Storj/metadisk-api/issues/14.
